[project]
name = "archivos-planos-csv-json"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.3.3",
    "tabulate2>=1.10.2",
]
